compressionLevel: mixed

enableGlobalCache: false

enableInlineHunks: true

enableTelemetry: false

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-compat.cjs
    spec: "@yarnpkg/plugin-compat"

supportedArchitectures:
  cpu:
    - current
    - x64
    - ia32
  libc:
    - current
    - glibc
    - musl
  os:
    - current
    - darwin
    - linux
    - windows

yarnPath: .yarn/releases/yarn-4.0.0.cjs
