enableInlineHunks: true

enableTelemetry: false

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-compat.cjs
    spec: '@yarnpkg/plugin-compat'

supportedArchitectures:
  os:
    - current
    - darwin
    - linux
    - win32
