name: Test
on:
  push:
    branches:
      - master
      # - development

  pull_request:
    branches:
      - master

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest] # windows-latest]
        node: ['18', '20']
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Github Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Setup bun
        uses: oven-sh/setup-bun@v1

      - name: Install
        run: bun install --immutable

      - name: Lint
        run: bun run lint

      - name: Test
        run: bun run test
        env:
          CI: true
          NEXT_TELEMETRY_DISABLED: 1

      - name: Build
        run: bun run build
        env:
          NEXT_TELEMETRY_DISABLED: 1
